# A replication? {#sec-areplication}

Let's start by discussing some terminology

- A **replication** of a result involves collecting new data in the same
  design and running the same analyses on the **newly collected data**
  (i.e. different data) to test the same hypothesis (or more broadly: to
  answer the same research question) as someone else did already.
  Typically, this is done by different researchers than the ones that
  came up with the result in the first place. If researchers replicate
  their own work, this is called a self-replication.

- A replication is related to but different from a **reproduction** of
  someone's work (which we will discuss in more detail in Section
  \@sec-reproducibility). This involves someone else running the same
  analyses on the **already collected data** (i.e., the same data; with
  code either self-written or provided by the original researchers, or
  something in between).

Not that this is the terminology I will stick to in these notes, but
keep in mind that conventions differ across fields, disciplines, time,
researchers and vibes. For example, when in 2105 200 researchers
(including myself) replicated 100 studies, they collectively thought
they were [[Estimating the reproducibility of psychological science]{.underline}](https://www.science.org/doi/10.1126/science.aac4716), while in fact they were checking replicability. 

Another terminological confusion relates to the sentence "Study X has
been replicated". Typically, it just means that someone has tried to do
the study again. It doesn't say anything about the results that someone
has found. When that someone found the same results (by whatever
criterion; see @sec-designinganalysis), you would read "Study X was successfully
replicated", and if the results were different, you would read "Study X
failed to replicate". Somehow, i would interpret "Study X has been
reproduced" as "Study X has been successfully reproduced" but it might
be just me.

So, basically, when you do a replication, you will be doing an
earlier study again. Let\'s introduce some more terminology. The study
you will do again aka replicate will be referred to as *the original
study (OS)*, and its authors as, wait for it, *the original authors
(OAs)*. I have tried to suppress my gangsta desire to use O.G. study and
O.G. authors, but I can\'t promise I\'ve always succeeded.
