# Desiging your analysis {#sec-designinganalysis}

\^ Even if the OAs were transparent or kind enough to share their
detailed processing analysis steps or code, don't just assume the best
course of action is to use just this exact processing and analytical
approach and shared code. It might still makes sense to do something
different than the OAs and go beyond the exact same processing analysis
steps or code as used by the OAs.

- Your quality check from Section \@sec-checkingquality, your visual
  check from Section \@sec-checkingvisuals, your numerical conformity
  check from Section \@sec-checkingconformity, and your re-analysis from
  Section \@sec-reanalyzing might have revealed the need to do things
  differently, because the OAs did something weird or wrong.

- And even if all the answers to the questions asking "was so-and-so
  done correctly?" are "hell, yeah", now is the time to ask, can
  so-and-so be done better (see also \@sec-alternative)? Are
  there analyses available for the same test that are more appropriate
  and have e.g. better statistical properties? xxx current state of the
  art xxx TODO add example

- So, in light of the fact that people do stuff that is weird and wrong,
  and that the field has matured (or you are just better educated than
  the OAs are), you should consider doing an alternative or improved
  analysis compared to the OAs (constructive replication).

- (Of course, doing an extended study with e.g. an additional covariate
  is reason enough already why you can not just blindly redo the
  analyses from the OAs.)

\^ If your analysis will be different from the original ones and the
original raw data are available, it make sense to do your analysis and
their old data as well to facilitate comparison (see Section XXX)

\^ Similarly, it might be a good idea to perform the analyses as done by
the OAs on your data, next to your analysis and your data, explaining
the differences and why they are justified

\^ You still have the document with a list of the **known differences**
between your study and the original study I suggested you'd keep? Good!
Make sure to update it when thinking about your analyses.

\^ A big question is whether your tests should be one tailed or two
tailed. If you believe the OAs have provided some credible evidence for
the effect you are investigating, one-sided tests would make sense, I
guess. But I don't have any solid advice on this one. Maybe I should do
some reading up about it. In the absence of that, you should do that
yourself.

\^ Remember all the nagging questions I raised in Section
\@sec-ambiguous talking about how doing the same is often ambiguous and
can have at least two meanings, the same choice vs the same strategy? To
be clear, I don't have the answers to these questions raised. But these
are things that you will come across and will need to make decisions
about. Sometimes the answer will be: do several things, all of which
implement the idea of *the same* to some extent (i.e., the choice-same
and the strategy-same). So often, it might be interesting to do the main
analyses several times.

\+ Consider for example this scenario: the OAs correlate two measures,
each of which are a subscale. The scores on each subscale are determined
using a factor analysis, in which the items load on different factors
than the authors of the scale proposed/intended. This means there are at
least three plausible ways to compute the subscale for your data .

1)  use the scale structure as proposed by the scale developers

2)  use the scale structure as revealed by the OAs factor analysis

3)  use the scale structure as revealed by doing a factor analysis on
    your data

You can do these 3 options for both subscales. You could then look at 9
correlations, combining all 3 approaches. Or you could look at 3
correlations (approach 1 for subscale 1 and approach 1 for subscale 2;
approach 2 for subscale 1 and approach 2 for subscale 2; approach 3 for
subscale 3 and approach 1 for subscale 2). It's up to you how far you
want to go (between 1 and 9 analyses).

\^ If you take a different analytical strategy than the OAs, it often
makes sense to do the analyses of the OAs as well, as this facilitates
comparability.

\^ A big question to consider is how you will **evaluate replication
success**. When it is money time, you will need to answer the question:
was the replication attempt a success or a failure? Broadly speaking,
you want to compare your result to the original results and assess
whether your result either supports/confirms/converges/is consistent
with xxx or contradicts/diverges from the original result (or is
inconclusive).

\^ Well, like with everything, it depends how you measure and define
success.

Here is an you could do that
[[overwhelmingly large bunch of ways]{.underline}](http://rachelheyard.com/reproducibility_metrics/#table) you could do that. Among all of these variants, these two stand out:

- p-value based: Do you find a significant result when the OAs did, in
  the same direction?

- effect size based: Is your effect size inside the confidence interval
  of the effect size in the OS?

\^ Most of the above metrics concern a single
hypothesis/effect/test/research question. The study you replicated
probably contained many, such as an interaction effect followed up by a
simple effect. That means that your overall conclusion about the
replication study can (or most likely, often will be) mixed, in the
sense that some results converged but others did not.
