# Finding information about published research {#sec-findinginformation}

\^ A large part of doing a replication study involves finding resources
about the study you decided to replicate.

\^ The first thing you need to find if you want to replicate a study is
of course the paper describing the research process and results. Your
first go-to for finding a paper will be google, google scholar, and your
university (online) library. If you can't find the pdf of a paper in the
online library, and if you want to avoid illegal sites, take extra care
to avoid sci-hub, because you will find a lot of illegal papers there
and who would want that?

\^ Now that you have the paper, you would hope that you now have access
to all the information about the OS, such as info about the experimental
procedure, the exact research materials (e.g., stimuli, questionnaires)
used, the data processing steps, etc. I am sorry to have to crush your
hopes. As you will soon see, academic reporting is shockingly and
embarrassingly bad, scattered and incomplete. Sadly, not all information
about a study is neatly contained in the published paper. *If* the info
you need is even reported (and you should consider yourself lucky if
that is the case!), it will most likely be scattered around the academic
universe.

\^ Here is a non-exhaustive traveler's guide to places where you might
or might not find the info you are looking for. Note that not all these
associated resources are available for all papers. In these spots, you
might find code shared by the original authors, their preregistration
protocol, their research materials, their data, results of any
additional analyses, etc

- the appendix of the paper

- the supporting information/supplemental materials of the paper (often
  found with the electronic version of the paper, such as
  [[https://journals.sagepub.com/doi/10.1111/j.1467-9280.2008.02136.x]{.underline}](https://journals.sagepub.com/doi/10.1111/j.1467-9280.2008.02136.x))

- the journal's website

- ideally (but very seldomly), the authors share (part of) their
  materials, data, etc on a third-party platform or repository.

  - for example, the open science framework, osf.io. osf.io is one of
    the many platforms that researchers use to share e.g., data,
    materials etc. if there is an associated osf project page, there
    will be a link in the paper if there is an associated osf project
    page. keep an eye out for in paper osf.io links, such as
    [[https://osf.io/ivfu6/]{.underline}](https://osf.io/ivfu6/).

  - keep in mind that there are many others (e.g., figshare; zenodo). so
    read the paper carefully looking for clues

  - github/gitlab accounts of the OAs

- the personal websites of the OAs or the websites of their research
  groups or labs

- some studies come with a pre-registration plan, which might provide
  additional cues. If they do, it will most likely be advertised in the
  paper, with a link to a [[osf.io]{.underline}](http://osf.io) project
  or [[aspredicted.org]{.underline}](http://aspredicted.org) project.

\^ In some cases, the same data set is used in several papers by the
same authors. You would think that the description of the study would be
the same in both papers, but you should stop thinking really. You might
hope (you can still hope!) that when this happens, the authors would
just copy their earlier text when reusing it, but there is surprisingly
little cross-paper-consistency, and if your OS is lacking in detail, you
might get lucky that another paper using the same data set is a bit more
loose-lipped in exactly how the data were collected and processed.

\^ Of course, when seaching for these additional sources, google is your
friend (though evil). Be creative!

\^ A last resort for finding info about the OA is asking them. You
should thread lightly though, which is why there is a full section for
that (see  \@sec-contacting).

\^ Fully understanding how the study was performed probably involves
piecing together several sources of information. For example, the OAs
might not have mentioned in the paper they deleted cases with missing
data, so you only realize that when you inspect their code; or the OAs
might not have mentioned anything about attention checks in the paper,
and only by inspecting the raw data, you find out that they included 3
attention check items. Since sources are scattered, I advise to keep
track of all details of the original study in a separate document and to
add the source for each aspect you are discussing.

