# Interpreting your result

\^ What if your replication failed, by whatever the metric you prefer? If you don't find the same results as the original authors, what now? Think of what might have caused or contributed to this. There are many possible explanations or reasons for why your results may differ from theirs.

-   The original effect was a false positive

-   Your result is a false negative

-   The different result might be caused by the inevitable differences between the OS and your study. When discussing this, it makes sens to make a distinction between differences that are known before data collection and analysis (i.e., by design) or unknown (e.g., differences in gender distribution; differences in attrition rate) differences with the OS.

-   If you come up with a hidden moderator to explain the different result, try to turn it into a testable hypothesis that you then recommend as a suggestion for future research. If possible, discuss how the known and surprising differences with the original study might have influenced the results. How important are the (inevitable) differences between your study and the original one? And is it possible, feasible, and interesting to test this?

-   fig 4.2 en 7.1 xxxx
