# The same? {#sec-thesame}

<!-- todo later xxx a bit like correcting bugs vs adding features in software
development-->

\^ While the idea of *doing everything the same way the original
authors* *did* seems ideal (at least in terms of deciding what to do),
in practice, it is guaranteed to turn out to be much more muddy. A lot
of work in the definition of a replication is done by the word *same*.
There\'s a lot to say about that. Below, I\'ll try to say a few bits. As
I explain below, 1) it can be very hard if not impossible to do things
the same; 2) it can be hard to judge whether or not you actually do the
same 3) it can be plain stupid to do the same!

## doing the same is impossible or infeasible {#sec-impossible}

\^ First, doing everything the same is sometimes infeasible or even
downright impossible. Even if you would like to do everything the OAs
did exactly again, your study inevitably *will* differ from the original
one!

\^ You, for example, will have different participants in your sample.
The people that participated in the OS are typically untraceable. There
will inevitably be a difference in the sample you use.

\^ What's worse, you might live in a different **place** than the OAs.
So if the OS did not involve click workers and unless you are up for
academic travel, your sample will come from a different place and as a
result may have different characteristics like theirs, in terms of age,
gender, religion, culture, nationality and so on. You might live in a
different country than the OAs of the study you are replicating, where
the inhabitants might have different characteristics (such as
religiosity, level of conservatism, etc). your "general population"
might differ from their "general population". Or the OAs might have
studied the influence of xxx on social media use with students living in
dorms, but your local students population is not living in dorms. So
this means you might be sampling from a different **population**.

\^ As Bawb had told us, times, they are a-changin'. So another
difference you can not avoid unless you are Doc and drive a DeLorean, is
**time**.

\^ A similar reasoning relates to the **context** of the study. Some
studies focus on something that is very context dependent for which the
context is hard to recreate. Take, for example, a study on the mental
health during the March 2020 lockdown in Belgium. It will be hard to
recreate the exact circumstances in Belgium in March 2020. Even if you
are "lucky" to live through another lockdown, and study mental health
again in Belgium, your study will probably not be the same. Each
lockdown is different, in terms of build-up, severity of the disease,
groups of people being most affected, regulations, measures and policies
etc.

\^ Finally, maybe you don't have the same **means** as the OAs, which
could be due to the passage of time, or to the division of wealth, or
just other practical stuff getting in the ways. That makes doing the
same not impossible in general, but at least impossible for you. For
example, you do a study again but, for some technical reason, you use
pictures instead of film clips to invoke trauma. Or the OAs might have
collected their data over summer, but the practicalities of your data
collection makes it impossible for you to do so and you will have you do
your data collection during winter.

\^ There's a sadder reason than geography and physics why doing things
exactly the same might be impossible. These reasons are psychology and
sociology. It is often surprisingly hard to find out exactly what the
OAs did in all its glory **details**, as they tend to under-report what
exactly they did. Often, authors keep their readers in the dark about
lots of stuff, both big and small. Things have gotten slightly better
recently, but no one is adding this info retroactively to their
imprecisely reported studies! And of course, if you don't know what the
OAs did, how can you do it again? Do you want an example? I have more
than you wished for!

- If the OAs included a subscale of measure D in their analyses, did
  they only present the relevant items to the participants, or did they
  present the full set of items and only analysed the data for the
  subscale?

- When doing an independent samples t-test, did the OAs use the Student
  version (assuming equal variances) of the Welch version (not assuming
  equal variances)? When doing a Pearson's Chi-squared test, did they
  use a continuity correction or not? Which type of ANOVA (I, II or III)
  was done?

- How were missing data treated? How were outliers treated? How were
  they defined?

- Which exact inclusion or exclusion criteria did the OA use?

- What were the exact test instructions?

- Did the model include an interaction? Which estimator was being used?

- The OAs know, but they won't tell you! Or more likely, they won't
  know. They won't tell you and you will need to guess! TODO add more
  examples from Artner et al. (2021).

- etc

\^ So because authors are often terribly unspecific in their methods
description, it will often be unclear what the OAs did. So the default
"do as they did" doesn't work here. We could ask them, but still, and
shockingly, it often remains unclear! If the OAs were unspecific in
their reporting at the time of their reporting, and they are now
non-communicative when prompted for details or simply don't remember the
details themselves, your glorious road to sameness abruptly ends.

## doing the same is ambiguous {#sec-ambiguous}

\^ The same and the same are not the same. Even if you ignore the
inevitable differences between now and then, and you go full Nancy Drew
and you do find out exactly what the OAs have been doing, it is often
simply unclear what *doing the same* exactly means. This has to do with
the fact that "the same" can have two different meanings: you can either
make the same *choice* as the OAs made, or you can follow the same
*decision* *strategy* as the OAs did. Those both routes do not
necessarily lead to the identical steps! Here are some examples I
encountered when doing replications, just to give you a feel:

- The OAs make weird choices in data collection without justification,
  such as rewording items or instructions compared to the "official"
  source, or add an item of their own making, or inexplicably dropped an
  item. Do you make the same weird choice or do you follow the same
  strategy of assessing construct X with tool Y and thus follow the
  manual?

- Back in the 80s, the OAs paid their participants \$20 for a short
  task, which was quite a sizeable sum at the time. Do you make the same
  choice and pay the same amount (in your local currency) or do you
  follow the same strategy and pay "a lot" too (whatever that currently
  means) and xxx incentives remuneration if the effect depends on it, it
  should be equally high. moet lager. dit is over dat het een verschil
  kan zijn. en dat het mss chice vs stratey xxx

- The OAs make weird choices in data processing without proper
  justification, such not including the answer to a specific item when
  constructing the sum score, contrary to what the manual for the
  questionnaire tells prescribes. Do you make the same weird choice or
  do you follow the same strategy of assessing construct X with tool Y
  and thus follow the manual?

- The OAs report that, at the time of the OS, there was a better (in
  whatever sense) version of the questionnaire than the one they used,
  but the OAs didn't include the superior version because it was too
  long and the OS was part of a larger data collection which couldn't
  afford to include the long version. If time is not such an issue for
  your study, do you use the short, inferior version or the long
  superior version?

- The OAs include a measure C in their data collection, but do not
  report the analyses about C, citing low reliability in their sample as
  the reason. Should you make the same choice and also not include C in
  your data analysis, and hence not even in your collection? Or should
  you follow the same strategy, and include it in the data collection
  and inspect its reliability? And what should you do if you include it
  but reliability is high?

- The OAs remove an item from their scale because doing so increases the
  Cronbach's alpha. Do you make the same choice and remove the item as
  well, or do you follow the same strategy, and only remove it when
  doing so increases alpha? And what if the gain when an item was
  deleted was high in the OS (say, from .49 to .77) but small in yours
  (from .63 to .65)?

- The OAs combine two subscales into a total score because of the high
  correlation between them. In your study, correlation is low. Do you
  combine (same choice) or not (same strategy). And what exactly counts
  as high?

- The OAs split their sample in a high and a low group using a mean
  split. Do you use their mean (same choice) or your mean (same
  strategy)?

- The OAs use two measures, each of which are a subscale, with the
  scores on each subscale being determined using a factor analysis. Do
  you use the scale structure as revealed by the OA factor analysis
  (same choice) or rather the scale structure as revealed by doing a
  factor analysis on your own data (same strategy)?

- The OAs only include variables as a covariate in their model based on
  a significant correlation with some other variable. Do you include
  only those covariates the OAs included (so you make the same choice as
  the OA did) or do you only include covariates that were significantly
  correlated in your data set (so you follow the same strategy as the OA
  did)?

<!-- -->

- The OAs only include covariates in their model if they have a
  significant correlation with the outcome variable. Do you use the
  exact same covariates as the OAs, regardless of significance (same
  choice), or do you use the same procedure as the OA, meaning you only
  include the variables with a significant correlation in your data
  (same strategy)? TODO merge with previous

<!-- -->

- The OAs derived four clusters of participants, based on their data. Do
  you make the same choice and use the same number of clusters and the
  same cutoff, or do you follow the same strategy and make a possible
  different number of clusters of your own, based on your own data?

- etc

\^ The *the same is not the same as the same* problem is further
amplified by what we tend to celebrate: **scientific progress**. There
is a good chance that since the OS the state of the art about data
collection, data processing and data analysis has changed. Science
progresses, you know. Especially for older papers, it makes sense to use
different materials or analyses altogether.

- Maybe there is now an updated, better version of the stimulus set or
  questionnaire the OAs used. Do you make the same choice and use the
  old version, or the same strategy and use the updated version?

- Maybe there is a new (and possibly better) questionnaire assessing the
  same construct or concept altogether, so not just an updated version
  of the questionnaire the OAs used. Do you make the same choice and use
  the questionnaire used but the OAs (using questionnaire X), or the
  same strategy and use the new questionnaire (assessing construct Y)?
  If the OAs measured depression with questionnaire A, but now, years
  later, questionnaire B for measuring depression turns out to be better
  in some sense, is using A the same (using the same choice of
  questionnaire) or is using B the same (using the same strategy of
  assessing the depression using a questionnaire)? TODO merge with
  previous

- Maybe the OAs did an analysis which is ok but could be improved upon,
  either because you just had a better education, or new tools have been
  developed since the OS. Do you stick to the ok analyses (making the
  same choices) or do you go for the new and improved ones (following
  the same strategy of testing the hypotheses using appropriate tools)?
  TODO add example

\^ Another reason why *doing the same* can be ambiguous is that there is
sometimes, embarrassingly, more of the same. Some OAs underreport,
others overreport.

- The OAs report in their paper a few examples items of their survey.
  They also shared their study materials with the world. Great! But what
  if the reported items are not identical to the shared items? Which
  ones should you use if you want to do the same?

- The OAs report in their paper using a Welch t-test. They also shared
  their code with the world. That's awfully nice! But what if the code
  shows they used a Student t-test, and you don't have the raw data to
  check which version they actually uses? Which version should you use
  if you want to do the same?

\^ To be clear, I don't have the answers to these questions raised when
discussing ambiguity. Sometimes the answer will be: do several things,
all of which implement the idea of *the same* to some extent. But these
are things that you will come across and will need to make decisions
about. So often, it might be interesting to do the main analyses several
times (see also \@sec-designanalysis).

## doing the same is not ideal or undesired {#sec-sec-undesired}

\^ The previous examples focused on cases where something better is
available, but the original approach was not terrible. Sometimes,
however, scientific **progress** is so clear that doing the same as in
making the same choice is simply undesired. Which is what I discuss
next. In these cases, doing exactly the same as the OAs is perfectly
possible, but doing so would actually be bad form! xxx

\^ You might have decided to use a different population, such as
nationality (which, as per above, might or might not mean you are still
doing a replication). Clearly, replicating an OS which was done in
Portugal with Portuguese materials with your Dutch speaking participants
will give you a very high score on sameness, but would be a very bad
idea. This means that you might need to do things in a different
language than the OAs, which means you will have to find translated
materials or possibly do the translation yourself.

\^ xxx A final instantation of the ambiguity of *same* is a result of
the OS (probably) being set in a different time and place. In some
situations, there is again the option of using the literal original
material (same choice) or you might need to "translate" the study to a
current, local context (same strategy).

Even is the measure is perfectly fine, you might still not be off the
hook. In some situations, you might need to "translate" the study to a
current, local context

- Say you want to assess interests in sports in general and use a
  Flemish population. The OAs did their study in the 80s in the US. If
  the OS used a dropdown menu with popular sports and asked the
  participants to select which they like (to assess interests in sports
  in general), that list might represent popular US sports in the 80s.
  You might want to use popular sports in current-day Flanders!

- One of my students attempted to replicate a study from 1999 on the
  relationship between attachment styles and parasocial behavior. To
  assess parasocial behavior, the OAs made use of a questionnaire
  published in 1992 with items like "I think my favorite TV personality
  is like an old friend". To a 2023 audience, this sentence probably
  reads like a question about your favourite gladiator, so the outdated
  term "TV personality" should be updated to current day celebrities and
  media personalities like influencers.

\^ These sorts of problems call for the use of positive or negative
controls, or piloting.

\^ Also, there is a non-negligible chance that the OAs did something
wrong or stupid (I should watch my language. Maybe I should go and read
Section \@sec-writing) when designing their study and analyzing their
data so the OS suffers from serious methodologcal shortcomings. After
all, they are human too!

- The OAs might have overlooked a confound.

- The OAs might have not used an appropriate measure

- The OAs did not include an important control variable they really
  should have

- The measures used by the OAs could, for example, be of questionable
  psychometric quality (such a reliability of validity)

- They could not correspond to the construct of interest

- They could not be appropriate for the population under study

- TODO: add example birthe

- In Sections \@sec-reproducibility and \@sec-checkingquality, I list
  some common statistical fallacies and mistakes, but obviously the
  catalogue is much larger.

If this happened, it would be unwise to make the same mistake,
especially if a better option is available. *They* may have done stupid
things that are deeply flawed, but *you* are not making these **errors**
that again.

\^ But even when the OAs didn't do something wrong or stupid, there is
no reason to just relax. Remember how I told you science progresses? I
still stand behind that statement! Maybe, and more generously, what they
did made perfect sense at the time of their study, but now we realize
they were flawed.Not because what they did was good, you shouldn't aim
for better. Don't let the good be the enemy of the better! So even if
their design, materials, and analysis was appropriate, you migh want to
look further so that your study reflects current best practices. For
example, TODO: add example.

- For example, maybe the OS was done in a time where attention and
manipulation checks weren't customary. This does not mean your study
should not include some (there are reasons, though, to not include it
xxx)

- There are better stimuli, questionnaires, tools, techniques and
  statistical approaches available now.

## doing the same is not your current interest {#sec-nointerest}

\^ Everybody is unique and, somewhat contradicting to that claim, you
are no exception to that. So you might have slightly different interests
than the OAs. Sometimes, you don't want to do the same, because you are
interested in something different than the OAs. Or, you might feel
forced, by whatever academic pressure, to not "just" do a replication
study because that is taken to mean by some people you have a boring,
uncreative, nasty and kleptomanic personality. So maybe in your study,
you *want* things to be different. As per above, the difference might be
relevant enough to no longer count as a replication study.

\^ You might be interested in a different population. You could end up
doing a study again (with the same research questions, materials,
experimental design and analytic plan) but in a different population
(e.g., with Europeans or Belgians instead of with Americans; or with
golf players instead of with soccer players; and so on) or in a
different field (e.g., in math education instead of in language
education xxx; visual memory to auditory memory; from face-to-face
impressions to online impressions xxx).

- The OAs investigated the mental health among professional soccer
  players and made their conclusion about soccer players (and not about
  sportsmen in general). You, on the other hand, might be interested to
  do the same study again with professional golf players and your
  conclusion will be about golfers (and not about sportsmen in general).
  That's not replicating, despite doing most of the things exactly the
  same. xxx

- The OAs investigated the impact of various types of sex education in
  Portugal. You might be very interested in doing the same study in
  Belgium. Since at least the formal sex education in Portugal is
  organised differently than in Belgium, if you do the study again in
  Belgium, that's not replicating, despite doing most of the things
  exactly the same. xxx

- The OAs studied young adults and found a relationship between social
  media use and loneliness. You do the same study again but in a general
  population or an elderly population or with kids. This might no longer
  count as a replication, depending on the extent to which the OAs
  stressed that their conclusion is limited to young adults. xxx

\^ Of course, changing the population of interest might mean you need to
change other stuff. A survey targeted at soccer players most likely
contains slightly different items than at golf players; doing a study
with kids that invoked trauma using film clips should probably use
different film clips to invoke trauma if it involves adults; etc

\^ You might be interested in a different approach: Does xxx only work
with film clips or also with text xxx? Or does the crowd within effect
gets bigger when the delay is longer?

\^ Maybe you want your study to be more informative than theirs. For
example, you might want to include additional factors or variables that
the OAs did not consider.

- For example, if the OA showed that self-compassion significantly
  predicted changes in depression symptoms, you might want to test that
  relation again using the same materials, procedure, and analyses, but
  additionally want to include stress as an additional predictor. In
  your analyses, however, you could also just do the original analysis
  with just self-compassion as a predictor. If you do so, your study
  will both be a replication and an extension. xxx

## ok, i get it. can we wrap up, please?

\^ So say you do a replication and the OAs were kind enough to share all
their study materials and all their analysis code. This might sound like
you have hit the replication jackpot! Your first instinct might be to
just use all of that and call it a day. After all, the point is to do
the same as what they did, right? I hope to have shown you that this is
not always the best course of action, and that there might be reasons to
do things differently.

- You might want to go and look for the "official" version of the
  stimulus set, survey or questionnaire (because the OAs might have
  deviated from this version, for no good or no justified reason).

- You might want to look for different existing materials than the
  materials shared by the OAs (because there might be better materials
  available by now, or they were constrained by practical reasons for
  using a lesser version and you are not).

- You still might need to create your own materials (because their
  materials might be sub par or you might not have the machines or
  expertise to use it or you need to translate it or adapt it to current
  place and time and population).

- You might still want to think for yourself about a good research
  design (because there might be a confound in theirs).

- You still might wish to write your own code (because the OAs might
  have made a mistake in theirs or might not have used the best analysis
  available).

So much for "just doing the same". So while in an ideal world, you can
simply do *everything just like the original authors did*, I hope to
have warned you by now that often, it won't be that simple.

\^ Also, note that there are many aspects to a study. Your study might
be the exact same in the materials used, but not in the design. Or you
might test the same hypothesis, but using different analyses. All this
leads to a vast array of types of replications. But these fine grained
distinctions are not only hard to make but also relatively
uninteresting. The most important take-away is 1) that you should not
panic if you can't do things the same 2) that doing the same is not
always a good, let alone the best, idea

\^ Since we are on the topic of warnings, here's another warning you
didn't know you needed. As HRSS writes, "Ideally, being replicated would
be an honor for authors since other researchers deem their findings
important but a failed replication could potentially harm the reputation
of the original and increase distrust towards them among their peers".
So while you think you are doing a service to science, not everybody
will agree. Some people might consider you a nagging, rude, wasteful
creature lacking any creativity. There's not much that can be done about
it, but it's good to keep that in the back of your mind.
